import React, { useEffect, useState, useMemo } from 'react';
import { fetchTableData, guessFieldMapping, guessTimekeepingMapping, guessPersonnelMapping } from './services/api';
import { SaleRecord, SalesStats, FieldMapping } from './types';
import { APP_ID, API_KEY, TABLE_NAME, CUSTOMER_TABLE_NAME, TIMEKEEPING_TABLE_NAME, PERSONNEL_TABLE_NAME, REVENUE_EXPENSE_TABLE_NAME, CURRENCY_FORMAT } from './constants';
import { Stats } from './components/Stats';
import { SalesTable } from './components/SalesTable';
import { SalesChart } from './components/SalesChart';
import { LayoutDashboard, LogOut, Settings, Bell, Database, Users, ShoppingBag, Clock, Calendar, Filter, Download, ChevronLeft, User, ArrowRight, Table as TableIcon, List, Grid3X3, AlertCircle, X } from 'lucide-react';

// Helper function to parse date from mm/dd/yyyy format
const parseDate = (dateStr: string | number | Date): Date | null => {
  if (!dateStr) return null;
  
  // If already a Date object
  if (dateStr instanceof Date) {
    return isNaN(dateStr.getTime()) ? null : dateStr;
  }
  
  // If it's a number (timestamp)
  if (typeof dateStr === 'number') {
    const date = new Date(dateStr);
    return isNaN(date.getTime()) ? null : date;
  }
  
  // Parse string format mm/dd/yyyy
  const str = String(dateStr).trim();
  
  // Try mm/dd/yyyy format first
  const mmddyyyyMatch = str.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (mmddyyyyMatch) {
    const [, month, day, year] = mmddyyyyMatch;
    const date = new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
    if (!isNaN(date.getTime())) {
      return date;
    }
  }
  
  // Fallback to standard Date parsing
  const date = new Date(str);
  return isNaN(date.getTime()) ? null : date;
};

const App: React.FC = () => {
  const [salesData, setSalesData] = useState<SaleRecord[]>([]);
  const [customerData, setCustomerData] = useState<SaleRecord[]>([]);
  const [timekeepingData, setTimekeepingData] = useState<SaleRecord[]>([]);
  const [personnelData, setPersonnelData] = useState<SaleRecord[]>([]);
  const [revenueExpenseData, setRevenueExpenseData] = useState<SaleRecord[]>([]);
  
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'sales' | 'customers' | 'timekeeping' | 'revenue-expense'>('sales');

  // Sales Date Filter State
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  // Customer Filter State
  const [startDateCustomer, setStartDateCustomer] = useState('');
  const [endDateCustomer, setEndDateCustomer] = useState('');
  const [selectedCustomerType, setSelectedCustomerType] = useState<string>('');

  // Timekeeping Filter State (Default to requested month 2026-02)
  const [selectedMonth, setSelectedMonth] = useState('2026-02');
  
  // Filter by Employee
  const [selectedEmployeeFilter, setSelectedEmployeeFilter] = useState<string>('');

  // State for Detail View (Drill down into an employee)
  const [selectedEmployee, setSelectedEmployee] = useState<string | null>(null);

  // Revenue-Expense Filter State (shared filter)
  const [startDateRevenueExpense, setStartDateRevenueExpense] = useState('');
  const [endDateRevenueExpense, setEndDateRevenueExpense] = useState('');

  // Hidden Columns Definitions
  const salesHiddenColumns = useMemo(() => [
    'Related Bán hàng CTs',
    'Related Thu chis',
    'Số Km',
    'Ngày nhắc thay dầu',
    'ĐÁNH GIÁ DỊCH VỤ',
    'id khách hàng',
    'ID',
    'SĐT',
    '_RowNumber',
    'Dịch vụ sử dụng',
    'id',
    'Loại phiếu',
    'id đơn'
  ], []);

  const customerHiddenColumns = useMemo(() => [
    'id',
    'Ảnh',
    'Danh sách mua hàng',
    '_RowNumber',
    'Related Bán háng' // Often auto-generated by AppSheet, safe to hide if present
  ], []);

  const revenueExpenseHiddenColumns = useMemo(() => [
    'id',
    'ID',
    '_RowNumber',
    'Related Bán hàng CTs'
  ], []);

  // Initial Data Fetch
  useEffect(() => {
    const loadData = async () => {
      try {
        setIsLoading(true);
        // Fetch all tables in parallel
        const [sales, customers, timekeeping, personnel, revenueExpense] = await Promise.all([
          fetchTableData(TABLE_NAME),
          fetchTableData(CUSTOMER_TABLE_NAME),
          fetchTableData(TIMEKEEPING_TABLE_NAME),
          fetchTableData(PERSONNEL_TABLE_NAME).catch(e => {
            console.warn("Could not fetch personnel table, falling back to timekeeping data only.", e);
            return [];
          }),
          fetchTableData(REVENUE_EXPENSE_TABLE_NAME).catch(e => {
            console.warn("Could not fetch revenue-expense table.", e);
            return [];
          })
        ]);
        
        setSalesData(sales);
        setCustomerData(customers);
        setTimekeepingData(timekeeping);
        setPersonnelData(personnel);
        setRevenueExpenseData(revenueExpense);
      } catch (err) {
        console.error(err);
        setError('Không thể tải dữ liệu. Vui lòng kiểm tra kết nối API Key/App ID.');
      } finally {
        setIsLoading(false);
      }
    };

    loadData();
  }, []);

  // --- Sales Logic ---
  const mapping: FieldMapping = useMemo(() => {
    if (salesData.length === 0) return { dateField: '', amountField: '', productField: '', quantityField: '' };
    return guessFieldMapping(salesData[0]);
  }, [salesData]);

  // Sort Sales Data by Date (Newest first)
  const sortedSalesData = useMemo(() => {
    if (!mapping.dateField || salesData.length === 0) return salesData;
    
    return [...salesData].sort((a, b) => {
        const dateA = new Date(a[mapping.dateField]);
        const dateB = new Date(b[mapping.dateField]);
        
        // Push invalid dates to the end
        const timeA = isNaN(dateA.getTime()) ? -Infinity : dateA.getTime();
        const timeB = isNaN(dateB.getTime()) ? -Infinity : dateB.getTime();

        return timeB - timeA; // Descending order
    });
  }, [salesData, mapping]);

  // Filter Sales Data by Date Range (Applied to Chart, Stats, and Table)
  const filteredSalesData = useMemo(() => {
    if (!startDate && !endDate) return sortedSalesData;

    return sortedSalesData.filter(item => {
        const rawDate = item[mapping.dateField];
        if (!rawDate) return false;
        
        const itemDate = new Date(rawDate);
        if (isNaN(itemDate.getTime())) return false;

        if (startDate) {
            const start = new Date(startDate);
            start.setHours(0, 0, 0, 0); 
            if (itemDate < start) return false;
        }
        
        if (endDate) {
            const end = new Date(endDate);
            end.setHours(23, 59, 59, 999);
            if (itemDate > end) return false;
        }

        return true;
    });
  }, [sortedSalesData, startDate, endDate, mapping.dateField]);

  const stats: SalesStats = useMemo(() => {
    if (filteredSalesData.length === 0) {
      return { totalRevenue: 0, totalOrders: 0, averageOrderValue: 0, topProduct: 'N/A' };
    }

    const { amountField, productField, quantityField } = mapping;

    let totalRevenue = 0;
    const productCounts: Record<string, number> = {};

    filteredSalesData.forEach(item => {
      let val = 0;
      if (amountField && item[amountField]) {
         if (typeof item[amountField] === 'number') val = item[amountField];
         else if (typeof item[amountField] === 'string') val = parseFloat(item[amountField].replace(/,/g, '')) || 0;
      }
      totalRevenue += val;

      if (productField && item[productField]) {
        const prodName = String(item[productField]);
        let qty = 1;
        if (quantityField && item[quantityField]) {
           qty = Number(item[quantityField]) || 1;
        }
        productCounts[prodName] = (productCounts[prodName] || 0) + qty;
      }
    });

    const totalOrders = filteredSalesData.length;
    const averageOrderValue = totalOrders > 0 ? totalRevenue / totalOrders : 0;
    const topProduct = Object.entries(productCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A';

    return { totalRevenue, totalOrders, averageOrderValue, topProduct };
  }, [filteredSalesData, mapping]);

  // --- Customer Logic ---
  const customerMapping = useMemo(() => {
    if (customerData.length === 0) return { dateField: '', customerTypeField: '' };
    const keys = Object.keys(customerData[0]).filter(k => k !== '_id');
    const lowerKeys = keys.map(k => ({ key: k, lower: k.toLowerCase() }));
    
    const findKey = (candidates: string[]) => 
      lowerKeys.find(k => candidates.some(c => k.lower.includes(c)))?.key || '';
    
    return {
      dateField: findKey(['ngày đăng ký', 'ngày đăng kí', 'ngay dang ky', 'ngay dang ki', 'registration date', 'ngày tạo', 'created', 'ngày', 'date']),
      customerTypeField: findKey(['loại khách hàng', 'loại kh', 'loai kh', 'loai khach hang', 'customer type', 'type'])
    };
  }, [customerData]);

  // Filter Customer Data by Date Range and Customer Type
  const filteredCustomerData = useMemo(() => {
    let filtered = [...customerData];
    
    // Filter by date range
    if ((startDateCustomer || endDateCustomer) && customerMapping.dateField) {
      filtered = filtered.filter(item => {
        const rawDate = item[customerMapping.dateField];
        if (!rawDate) return false;
        
        const itemDate = parseDate(rawDate);
        if (!itemDate) return false;

        if (startDateCustomer) {
          const start = new Date(startDateCustomer);
          start.setHours(0, 0, 0, 0);
          if (itemDate < start) return false;
        }
        
        if (endDateCustomer) {
          const end = new Date(endDateCustomer);
          end.setHours(23, 59, 59, 999);
          if (itemDate > end) return false;
        }

        return true;
      });
    }
    
    // Filter by customer type
    if (selectedCustomerType && selectedCustomerType !== '') {
      const typeField = customerMapping.customerTypeField || 'Loại KH';
      filtered = filtered.filter(item => {
        const customerType = String(item[typeField] || '').trim();
        return customerType.toLowerCase() === selectedCustomerType.toLowerCase();
      });
    }
    
    return filtered;
  }, [customerData, startDateCustomer, endDateCustomer, selectedCustomerType, customerMapping]);

  // Get list of customer types for filter dropdown
  const customerTypeList = useMemo(() => {
    if (!customerData || customerData.length === 0) return [];
    const typeField = customerMapping.customerTypeField || 'Loại KH';
    
    const uniqueTypes = new Set<string>();
    customerData.forEach(record => {
      const customerType = String(record[typeField] || '').trim();
      if (customerType && customerType !== '') {
        uniqueTypes.add(customerType);
      }
    });
    return Array.from(uniqueTypes).sort();
  }, [customerData, customerMapping]);

  // --- Revenue-Expense Logic ---
  const revenueExpenseMapping = useMemo(() => {
    if (revenueExpenseData.length === 0) return { dateField: '', amountField: '', typeField: '', descriptionField: '' };
    const keys = Object.keys(revenueExpenseData[0]).filter(k => k !== '_id');
    const lowerKeys = keys.map(k => ({ key: k, lower: k.toLowerCase() }));
    
    const findKey = (candidates: string[]) => 
      lowerKeys.find(k => candidates.some(c => k.lower.includes(c)))?.key || '';
    
    return {
      dateField: findKey(['ngày', 'date', 'time']),
      amountField: findKey(['số tiền', 'so tien', 'amount', 'total', 'tổng', 'thành tiền', 'thanh tien']),
      typeField: findKey(['loại', 'loai', 'type', 'thu chi', 'thu/chi', 'thu/chi']),
      descriptionField: findKey(['mô tả', 'mo ta', 'description', 'nội dung', 'noi dung', 'ghi chú', 'ghi chu'])
    };
  }, [revenueExpenseData]);

  // Sort Revenue-Expense Data by Date (Newest first)
  const sortedRevenueExpenseData = useMemo(() => {
    if (!revenueExpenseMapping.dateField || revenueExpenseData.length === 0) return revenueExpenseData;
    
    return [...revenueExpenseData].sort((a, b) => {
        const dateA = parseDate(a[revenueExpenseMapping.dateField]);
        const dateB = parseDate(b[revenueExpenseMapping.dateField]);
        
        // Push invalid dates to the end
        const timeA = !dateA || isNaN(dateA.getTime()) ? -Infinity : dateA.getTime();
        const timeB = !dateB || isNaN(dateB.getTime()) ? -Infinity : dateB.getTime();

        return timeB - timeA; // Descending order
    });
  }, [revenueExpenseData, revenueExpenseMapping]);

  // Filter Revenue Data (Thu only)
  const filteredRevenueData = useMemo(() => {
    let filtered = sortedRevenueExpenseData.filter(item => {
      const { typeField, amountField } = revenueExpenseMapping;
      const type = typeField ? String(item[typeField] || '').toLowerCase().trim() : '';
      
      // Check if it's revenue
      if (type.includes('thu') || type.includes('revenue') || type.includes('income')) {
        return true;
      }
      
      // If type is unclear, check amount sign
      if (!type || type === '') {
        let val = 0;
        if (amountField && item[amountField]) {
          if (typeof item[amountField] === 'number') val = item[amountField];
          else if (typeof item[amountField] === 'string') val = parseFloat(item[amountField].replace(/,/g, '')) || 0;
        }
        return val > 0;
      }
      
      return false;
    });

    // Apply date filter (shared filter)
    if (startDateRevenueExpense || endDateRevenueExpense) {
      filtered = filtered.filter(item => {
        const rawDate = item[revenueExpenseMapping.dateField];
        if (!rawDate) return false;
        
        const itemDate = parseDate(rawDate);
        if (!itemDate) return false;

        if (startDateRevenueExpense) {
          const start = new Date(startDateRevenueExpense);
          start.setHours(0, 0, 0, 0);
          if (itemDate < start) return false;
        }
        
        if (endDateRevenueExpense) {
          const end = new Date(endDateRevenueExpense);
          end.setHours(23, 59, 59, 999);
          if (itemDate > end) return false;
        }

        return true;
      });
    }

    return filtered;
  }, [sortedRevenueExpenseData, startDateRevenueExpense, endDateRevenueExpense, revenueExpenseMapping]);

  // Filter Expense Data (Chi only)
  const filteredExpenseData = useMemo(() => {
    let filtered = sortedRevenueExpenseData.filter(item => {
      const { typeField, amountField } = revenueExpenseMapping;
      const type = typeField ? String(item[typeField] || '').toLowerCase().trim() : '';
      
      // Check if it's expense
      if (type.includes('chi') || type.includes('expense') || type.includes('cost')) {
        return true;
      }
      
      // If type is unclear, check amount sign
      if (!type || type === '') {
        let val = 0;
        if (amountField && item[amountField]) {
          if (typeof item[amountField] === 'number') val = item[amountField];
          else if (typeof item[amountField] === 'string') val = parseFloat(item[amountField].replace(/,/g, '')) || 0;
        }
        return val < 0 || (val > 0 && !type.includes('thu'));
      }
      
      return false;
    });

    // Apply date filter (shared filter)
    if (startDateRevenueExpense || endDateRevenueExpense) {
      filtered = filtered.filter(item => {
        const rawDate = item[revenueExpenseMapping.dateField];
        if (!rawDate) return false;
        
        const itemDate = parseDate(rawDate);
        if (!itemDate) return false;

        if (startDateRevenueExpense) {
          const start = new Date(startDateRevenueExpense);
          start.setHours(0, 0, 0, 0);
          if (itemDate < start) return false;
        }
        
        if (endDateRevenueExpense) {
          const end = new Date(endDateRevenueExpense);
          end.setHours(23, 59, 59, 999);
          if (itemDate > end) return false;
        }

        return true;
      });
    }

    return filtered;
  }, [sortedRevenueExpenseData, startDateRevenueExpense, endDateRevenueExpense, revenueExpenseMapping]);

  // Calculate Revenue Stats
  const revenueStats = useMemo(() => {
    if (filteredRevenueData.length === 0) {
      return { totalAmount: 0, totalRecords: 0 };
    }

    const { amountField } = revenueExpenseMapping;
    let totalAmount = 0;

    filteredRevenueData.forEach(item => {
      let val = 0;
      if (amountField && item[amountField]) {
         if (typeof item[amountField] === 'number') val = item[amountField];
         else if (typeof item[amountField] === 'string') val = parseFloat(item[amountField].replace(/,/g, '')) || 0;
      }
      totalAmount += Math.abs(val);
    });

    return { totalAmount, totalRecords: filteredRevenueData.length };
  }, [filteredRevenueData, revenueExpenseMapping]);

  // Calculate Expense Stats
  const expenseStats = useMemo(() => {
    if (filteredExpenseData.length === 0) {
      return { totalAmount: 0, totalRecords: 0 };
    }

    const { amountField } = revenueExpenseMapping;
    let totalAmount = 0;

    filteredExpenseData.forEach(item => {
      let val = 0;
      if (amountField && item[amountField]) {
         if (typeof item[amountField] === 'number') val = item[amountField];
         else if (typeof item[amountField] === 'string') val = parseFloat(item[amountField].replace(/,/g, '')) || 0;
      }
      totalAmount += Math.abs(val);
    });

    return { totalAmount, totalRecords: filteredExpenseData.length };
  }, [filteredExpenseData, revenueExpenseMapping]);

  // Calculate Net Amount (Lợi nhuận)
  const netAmount = useMemo(() => {
    return revenueStats.totalAmount - expenseStats.totalAmount;
  }, [revenueStats, expenseStats]);

  // --- Timekeeping Logic ---
  const timekeepingMapping = useMemo(() => {
    if (timekeepingData.length === 0) return { employeeField: '', dateField: '' };
    const mapping = guessTimekeepingMapping(timekeepingData[0]);
    console.log('[Timekeeping Mapping] Sample row keys:', Object.keys(timekeepingData[0] || {}));
    console.log('[Timekeeping Mapping] Found mapping:', mapping);
    return mapping;
  }, [timekeepingData]);

  const personnelMapping = useMemo(() => {
    if (personnelData.length === 0) return { nameField: '' };
    return guessPersonnelMapping(personnelData[0]);
  }, [personnelData]);

  // Filter and Aggregate Timekeeping Data based on Selected Month
  const { filteredTimekeepingData, employeeStats, employeeDetailsMap } = useMemo(() => {
    // 1. Prepare Base List of Employees from 'Nhân sự' table
    // Use a Map for Name Resolution (Lowercase -> DisplayName) to handle case-insensitivity
    const nameResolver = new Map<string, string>();
    const masterEmployeeSet = new Set<string>(); // Set of canonical names

    if (personnelData.length > 0 && personnelMapping.nameField) {
      personnelData.forEach(p => {
        const rawName = String(p[personnelMapping.nameField]).trim();
        if (rawName) {
           const lowerKey = rawName.toLowerCase();
           if (!nameResolver.has(lowerKey)) {
             nameResolver.set(lowerKey, rawName);
           }
           masterEmployeeSet.add(nameResolver.get(lowerKey)!);
        }
      });
    }

    // 2. Filter Timekeeping Logs by Month
    let filteredLogs = [];
    if (timekeepingData.length > 0 && timekeepingMapping.dateField) {
      filteredLogs = timekeepingData.filter(record => {
        const dateVal = record[timekeepingMapping.dateField || ''];
        if (!dateVal) return false;
        const date = parseDate(dateVal);
        if (!date) return false;
        
        const recordMonth = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
        return recordMonth === selectedMonth;
      });
    }

    // 3. Aggregate Work Hours per Employee from Logs
    const recordsByEmployeeAndDate: Record<string, Record<string, number[]>> = {};

    filteredLogs.forEach(record => {
      const rawName = String(record[timekeepingMapping.employeeField || ''] || 'Unknown').trim();
      const lowerName = rawName.toLowerCase();

      // Resolve name: If in personnel list (ignoring case), use that display name. Else use raw.
      const empName = nameResolver.get(lowerName) || rawName; 
      
      const dateVal = record[timekeepingMapping.dateField || ''];
      
      if (dateVal) {
        const dateObj = parseDate(dateVal);
        if (!dateObj) return;
        
        const dateStr = dateObj.toISOString().split('T')[0]; 
        const timestamp = dateObj.getTime();

        if (!recordsByEmployeeAndDate[empName]) {
          recordsByEmployeeAndDate[empName] = {};
        }
        if (!recordsByEmployeeAndDate[empName][dateStr]) {
          recordsByEmployeeAndDate[empName][dateStr] = [];
        }
        recordsByEmployeeAndDate[empName][dateStr].push(timestamp);
      }
    });

    // 4. Calculate Stats Helper
    const calculateStats = (name: string, datesMap: Record<string, number[]> = {}) => {
      let totalHours = 0;
      // Capture Total Check-ins: Sum of all timestamps across all days
      let totalCheckins = 0; 
      // Count number of days with check-ins
      const daysWithCheckins = Object.keys(datesMap).length;

      const dailyDetails: any[] = [];

      Object.entries(datesMap).forEach(([dateStr, timestamps]) => {
        const count = timestamps.length;
        totalCheckins += count; // Accumulate total rows/check-ins found
        
        // Tính giờ: Trong cùng 1 ngày, lấy giờ sau trừ giờ trước (giờ cuối - giờ đầu)
        let hours = 0;
        const minTime = count > 0 ? Math.min(...timestamps) : 0; // Giờ đầu (giờ vào)
        const maxTime = count > 0 ? Math.max(...timestamps) : 0; // Giờ cuối (giờ ra)
        
        if (count >= 2) {
          // Nếu có ít nhất 2 timestamps, tính giờ = giờ cuối - giờ đầu
          hours = (maxTime - minTime) / (1000 * 60 * 60); // Giờ ra - Giờ vào
          totalHours += hours;
        }
        // Nếu chỉ có 1 timestamp, không tính giờ (chưa có giờ ra)

        dailyDetails.push({
          date: dateStr,
          checkIn: count > 0 ? new Date(minTime) : null,
          checkOut: count > 0 ? new Date(maxTime) : null,
          checkCount: count, // Store the count to display warnings
          hours: hours
        });
      });
      
      dailyDetails.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
      
      return {
        stats: {
          name,
          totalHours,
          daysWorked: daysWithCheckins, // Changed: Now counts number of days with check-ins
          totalCheckins: totalCheckins, // Total number of check-in records (sum of all checkCount)
          avgHours: daysWithCheckins > 0 ? totalHours / daysWithCheckins : 0
        },
        details: dailyDetails
      };
    };

    // 5. Merge Master List with Log Data
    const finalStatsArray: any[] = [];
    const finalDetailsMap: Record<string, any[]> = {};
    const processedNames = new Set<string>();

    // 5a. Process employees from 'Nhân sự'
    masterEmployeeSet.forEach(name => {
      const datesMap = recordsByEmployeeAndDate[name] || {};
      const { stats, details } = calculateStats(name, datesMap);
      finalStatsArray.push(stats);
      finalDetailsMap[name] = details;
      processedNames.add(name);
    });

    // 5b. Process employees found in 'Chấm công' but NOT in 'Nhân sự'
    Object.keys(recordsByEmployeeAndDate).forEach(name => {
      if (!processedNames.has(name)) {
         const { stats, details } = calculateStats(name, recordsByEmployeeAndDate[name]);
         finalStatsArray.push(stats);
         finalDetailsMap[name] = details;
      }
    });

    finalStatsArray.sort((a, b) => b.totalHours - a.totalHours);

    return { 
      filteredTimekeepingData: filteredLogs, 
      employeeStats: finalStatsArray,
      employeeDetailsMap: finalDetailsMap
    };
  }, [timekeepingData, personnelData, timekeepingMapping, personnelMapping, selectedMonth]);

  // Filter timekeepingData by month and employee - áp dụng cho bảng "Dữ liệu thô (Toàn bộ)"
  // Bộ lọc tháng và nhân sự sẽ áp dụng trực tiếp cho dữ liệu thô
  const filteredTimekeepingDataByEmployee = useMemo(() => {
    // Bước 1: Lọc theo tháng từ timekeepingData (dữ liệu gốc)
    let filteredByMonth = [];
    if (timekeepingData.length > 0 && timekeepingMapping.dateField) {
      filteredByMonth = timekeepingData.filter(record => {
        const dateVal = record[timekeepingMapping.dateField || ''];
        if (!dateVal) return false;
        const date = parseDate(dateVal);
        if (!date) return false;
        
        const recordMonth = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
        return recordMonth === selectedMonth;
      });
    } else {
      filteredByMonth = timekeepingData;
    }
    
    // Bước 2: Lọc theo nhân sự (nếu có chọn)
    if (!selectedEmployeeFilter || selectedEmployeeFilter === '') {
      return filteredByMonth;
    }
    
    if (!timekeepingMapping.employeeField) return filteredByMonth;
    
    // Filter by selected employee (case-insensitive, exact match)
    const filterNameLower = selectedEmployeeFilter.toLowerCase().trim();
    return filteredByMonth.filter(record => {
      const rawEmpName = String(record[timekeepingMapping.employeeField || ''] || '').trim();
      if (!rawEmpName) return false;
      
      const empNameLower = rawEmpName.toLowerCase().trim();
      return empNameLower === filterNameLower;
    });
  }, [timekeepingData, selectedMonth, selectedEmployeeFilter, timekeepingMapping]);

  // Get list of employees from bảng "Chấm công" trong AppSheet (timekeepingData) - lấy từ cột "Nhân sự"
  // Lấy danh sách nhân sự trực tiếp từ cột "Nhân sự" trong bảng "Chấm công" (timekeepingData - dữ liệu gốc)
  const employeeListForFilter = useMemo(() => {
    if (!timekeepingData || timekeepingData.length === 0) {
      console.log('[Employee Filter] No timekeeping data');
      return [];
    }
    
    if (!timekeepingMapping.employeeField) {
      console.log('[Employee Filter] No employeeField found. Available keys:', Object.keys(timekeepingData[0] || {}));
      console.log('[Employee Filter] Mapping:', timekeepingMapping);
      return [];
    }
    
    console.log('[Employee Filter] Using field:', timekeepingMapping.employeeField);
    
    // Lấy danh sách nhân sự duy nhất từ cột "Nhân sự" trong bảng "Chấm công" (AppSheet)
    const uniqueEmployees = new Set<string>();
    timekeepingData.forEach(record => {
      // Lấy từ cột "Nhân sự" trong bảng "Chấm công"
      const empName = String(record[timekeepingMapping.employeeField || ''] || '').trim();
      if (empName && empName !== '' && empName !== 'Unknown' && empName !== 'null' && empName !== 'undefined') {
        uniqueEmployees.add(empName);
      }
    });
    
    const result = Array.from(uniqueEmployees).sort();
    console.log('[Employee Filter] Found employees:', result.length, result);
    return result;
  }, [timekeepingData, timekeepingMapping]);

  // Recalculate stats based on employee names from Timekeeping table (AppSheet API)
  // Bảng tổng hợp công chỉ hạch toán các nhân sự có trong dữ liệu chi tiết (filteredTimekeepingData)
  const recalculatedEmployeeStats = useMemo(() => {
    const dataToUse = filteredTimekeepingDataByEmployee;
    if (!dataToUse || dataToUse.length === 0) return [];
    if (!timekeepingMapping.employeeField || !timekeepingMapping.dateField) return [];

    // 1. Extract unique employee names from filteredTimekeepingData (dữ liệu chi tiết)
    // Chỉ lấy những nhân sự có trong bảng "Dữ liệu thô (Toàn bộ)"
    const nameResolver = new Map<string, string>(); // lowercase -> display name (first occurrence)
    const employeeNames: string[] = [];
    
    dataToUse.forEach(record => {
      const rawEmpName = String(record[timekeepingMapping.employeeField || ''] || '').trim();
      if (!rawEmpName) return;
      
      const lowerKey = rawEmpName.toLowerCase();
      if (!nameResolver.has(lowerKey)) {
        nameResolver.set(lowerKey, rawEmpName);
        employeeNames.push(rawEmpName);
      }
    });

    // 2. Group records from filteredTimekeepingData by employee name (case-insensitive)
    const employeeRecordsMap: Record<string, any[]> = {};
    
    dataToUse.forEach(record => {
      const rawEmpName = String(record[timekeepingMapping.employeeField || ''] || '').trim();
      if (!rawEmpName) return;
      
      const lowerKey = rawEmpName.toLowerCase();
      const matchedName = nameResolver.get(lowerKey) || rawEmpName;
      
      if (!employeeRecordsMap[matchedName]) {
        employeeRecordsMap[matchedName] = [];
      }
      employeeRecordsMap[matchedName].push(record);
    });

    // 3. Calculate stats for each employee (based on employee names from timekeeping data)
    const stats: any[] = [];
    
    employeeNames.forEach(empName => {
      const records = employeeRecordsMap[empName] || [];
      
      // Count total check-ins (Số lần chấm) - total number of records from raw data
      const totalCheckins = records.length;

      // Calculate total hours by grouping by date and checking for pairs
      const recordsByDate: Record<string, number[]> = {};
      
      records.forEach(record => {
        const dateVal = record[timekeepingMapping.dateField || ''];
        if (dateVal) {
          const dateObj = parseDate(dateVal);
          if (!dateObj) return;
          
          const dateStr = dateObj.toISOString().split('T')[0];
          const timestamp = dateObj.getTime();
          
          if (!recordsByDate[dateStr]) {
            recordsByDate[dateStr] = [];
          }
          recordsByDate[dateStr].push(timestamp);
        }
      });

      // Calculate hours: Trong cùng 1 ngày, lấy giờ sau trừ giờ trước (giờ cuối - giờ đầu)
      let totalHours = 0;
      Object.values(recordsByDate).forEach(timestamps => {
        // Nếu có ít nhất 2 timestamps trong ngày, tính giờ = giờ cuối - giờ đầu
        if (timestamps.length >= 2) {
          const minTime = Math.min(...timestamps); // Giờ đầu (giờ vào)
          const maxTime = Math.max(...timestamps); // Giờ cuối (giờ ra)
          const hours = (maxTime - minTime) / (1000 * 60 * 60); // Giờ ra - Giờ vào
          totalHours += hours;
        }
        // Nếu chỉ có 1 timestamp, không tính giờ (chưa có giờ ra)
      });

      stats.push({
        name: empName,
        totalHours,
        daysWorked: totalCheckins, // Số lần chấm = tổng số records trong dữ liệu thô
        totalCheckins: totalCheckins,
        avgHours: totalCheckins > 0 ? totalHours / totalCheckins : 0
      });
    });

    return stats.sort((a, b) => b.totalHours - a.totalHours);
  }, [filteredTimekeepingDataByEmployee, timekeepingMapping]);

  // Helper to get days in month for matrix
  const getDaysArray = useMemo(() => {
    if (!selectedMonth) return [];
    const [y, m] = selectedMonth.split('-').map(Number);
    const daysInMonth = new Date(y, m, 0).getDate();
    return Array.from({ length: daysInMonth }, (_, i) => i + 1);
  }, [selectedMonth]);
  
  // Grand Totals Calculation - đếm trực tiếp từ bảng "Dữ liệu thô (Toàn bộ)" đã được lọc
  const grandTotalDays = useMemo(() => {
    // Đếm trực tiếp số bản ghi trong filteredTimekeepingDataByEmployee (Dữ liệu thô đã lọc theo tháng và nhân sự)
    return filteredTimekeepingDataByEmployee ? filteredTimekeepingDataByEmployee.length : 0;
  }, [filteredTimekeepingDataByEmployee]);
  
  const grandTotalHours = useMemo(() => {
    // Tính tổng giờ từ dữ liệu thô đã lọc
    // Logic: Trong cùng 1 ngày, lấy giờ sau trừ giờ trước (giờ cuối - giờ đầu), sau đó tổng lại
    if (!filteredTimekeepingDataByEmployee || filteredTimekeepingDataByEmployee.length === 0) return 0;
    if (!timekeepingMapping.employeeField || !timekeepingMapping.dateField) return 0;
    
    // Group records by employee and date, then calculate hours
    const recordsByEmployeeAndDate: Record<string, Record<string, number[]>> = {};
    
    filteredTimekeepingDataByEmployee.forEach(record => {
      const empName = String(record[timekeepingMapping.employeeField || ''] || '').trim();
      if (!empName) return;
      
      const dateVal = record[timekeepingMapping.dateField || ''];
      if (dateVal) {
        const dateObj = parseDate(dateVal);
        if (!dateObj) return;
        
        const dateStr = dateObj.toISOString().split('T')[0];
        const timestamp = dateObj.getTime();
        
        if (!recordsByEmployeeAndDate[empName]) {
          recordsByEmployeeAndDate[empName] = {};
        }
        if (!recordsByEmployeeAndDate[empName][dateStr]) {
          recordsByEmployeeAndDate[empName][dateStr] = [];
        }
        recordsByEmployeeAndDate[empName][dateStr].push(timestamp);
      }
    });
    
    // Calculate total hours: Trong cùng 1 ngày, lấy giờ sau trừ giờ trước (giờ cuối - giờ đầu)
    let totalHours = 0;
    Object.values(recordsByEmployeeAndDate).forEach(employeeDates => {
      Object.values(employeeDates).forEach(timestamps => {
        // Nếu có ít nhất 2 timestamps trong ngày, tính giờ = giờ cuối - giờ đầu
        if (timestamps.length >= 2) {
          const minTime = Math.min(...timestamps); // Giờ đầu (giờ vào)
          const maxTime = Math.max(...timestamps); // Giờ cuối (giờ ra)
          const hours = (maxTime - minTime) / (1000 * 60 * 60); // Giờ ra - Giờ vào
          totalHours += hours;
        }
        // Nếu chỉ có 1 timestamp, không tính giờ (chưa có giờ ra)
      });
    });
    
    return totalHours;
  }, [filteredTimekeepingDataByEmployee, timekeepingMapping]);
  
  // Đếm số nhân sự từ bảng "Dữ liệu thô (Toàn bộ)" đã được lọc
  const totalEmployees = useMemo(() => {
    if (!filteredTimekeepingDataByEmployee || filteredTimekeepingDataByEmployee.length === 0) return 0;
    if (!timekeepingMapping.employeeField) return 0;
    
    // Đếm số nhân sự duy nhất từ dữ liệu thô đã lọc
    const uniqueEmployees = new Set<string>();
    filteredTimekeepingDataByEmployee.forEach(record => {
      const empName = String(record[timekeepingMapping.employeeField || ''] || '').trim();
      if (empName && empName !== 'Unknown') {
        uniqueEmployees.add(empName.toLowerCase());
      }
    });
    return uniqueEmployees.size;
  }, [filteredTimekeepingDataByEmployee, timekeepingMapping]);


  const handleExportSummary = () => {
    if (recalculatedEmployeeStats.length === 0) return;
    
    // Timesheet Export
    const days = getDaysArray();
    const headers = ['Nhân viên', 'Tổng giờ', 'Số lần chấm', ...days.map(d => `Ngày ${d}`)];
    
    const rows = recalculatedEmployeeStats.map(stat => {
      const dailyHours = days.map(day => {
        const dayStr = `${selectedMonth}-${String(day).padStart(2, '0')}`;
        const detail = employeeDetailsMap[stat.name]?.find((d: any) => d.date === dayStr);
        return detail ? detail.hours.toFixed(1) : '';
      });
      
      return [
        `"${stat.name}"`,
        stat.totalHours.toFixed(2),
        stat.daysWorked,
        ...dailyHours
      ];
    });
    
    // Append Grand Total Row to Export
    const totalRow = [
       '"TỔNG CỘNG"',
       grandTotalHours.toFixed(2),
       grandTotalDays,
       ...Array(days.length).fill('')
    ];

    const csvContent = "data:text/csv;charset=utf-8,\uFEFF"
      + [headers.join(','), ...rows.map(e => e.join(',')), totalRow.join(',')].join('\n');
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Bang_Cham_Cong_${selectedMonth}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };


  const getCurrentTableName = () => {
    switch (activeTab) {
      case 'sales': return TABLE_NAME;
      case 'customers': return CUSTOMER_TABLE_NAME;
      case 'timekeeping': return `${PERSONNEL_TABLE_NAME} + ${TIMEKEEPING_TABLE_NAME}`;
      case 'revenue-expense': return REVENUE_EXPENSE_TABLE_NAME;
      default: return '';
    }
  };

  const clearSalesDateFilter = () => {
    setStartDate('');
    setEndDate('');
  };

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900">
      {/* Sidebar */}
      <aside className="w-72 bg-gradient-to-b from-slate-950/95 via-blue-950/95 to-slate-950/95 border-r border-yellow-400/20 fixed inset-y-0 z-20 hidden lg:flex flex-col shadow-2xl backdrop-blur-xl">
        <div className="h-24 flex items-center px-6 border-b border-yellow-400/20 bg-gradient-to-r from-slate-950/90 via-blue-950/90 to-slate-950/90 backdrop-blur-xl">
          <div className="relative">
            <img 
              src="https://www.appsheet.com/template/gettablefileurl?appName=Appsheet-325045268&tableName=Kho%20%E1%BA%A3nh&fileName=Kho%20%E1%BA%A3nh_Images%2F0d516988.%E1%BA%A2nh.125520.png"
              alt="Logo"
              className="h-14 w-14 mr-4 object-contain rounded-lg ring-2 ring-yellow-400/30 shadow-lg"
              onError={(e) => {
                e.currentTarget.style.display = 'none';
              }}
            />
            <div className="absolute inset-0 rounded-lg bg-gradient-to-br from-yellow-400/20 to-transparent pointer-events-none"></div>
          </div>
          <div className="flex flex-col">
            <span className="text-xl font-bold bg-gradient-to-r from-yellow-300 via-yellow-400 to-yellow-300 bg-clip-text text-transparent tracking-tight">
              Anh Công nhân
            </span>
            <span className="text-xs text-blue-300/60 font-medium mt-0.5">Quản lý dữ liệu</span>
          </div>
        </div>

        <div className="flex-1 py-6 px-4 space-y-2 overflow-y-auto custom-scrollbar">
          <nav className="space-y-2">
             <button 
                onClick={() => setActiveTab('sales')}
                className={`group flex items-center w-full px-4 py-3.5 rounded-xl font-semibold text-sm transition-all duration-300 ${
                  activeTab === 'sales' 
                    ? 'bg-gradient-to-r from-yellow-400/20 to-yellow-500/10 text-yellow-300 border border-yellow-400/40 shadow-lg shadow-yellow-400/20 scale-[1.02]' 
                    : 'text-blue-200/80 hover:bg-blue-800/40 hover:text-yellow-300 hover:scale-[1.01] border border-transparent hover:border-yellow-400/20'
                }`}
             >
              <ShoppingBag className={`w-5 h-5 mr-3 ${activeTab === 'sales' ? 'text-yellow-400' : 'text-blue-300/60 group-hover:text-yellow-400'}`} />
              <span>Bán hàng</span>
              {activeTab === 'sales' && (
                <div className="ml-auto w-2 h-2 rounded-full bg-yellow-400 animate-pulse"></div>
              )}
            </button>
             <button 
                onClick={() => setActiveTab('customers')}
                className={`flex items-center w-full px-4 py-3 rounded-lg font-medium transition-colors ${activeTab === 'customers' ? 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30' : 'text-gray-300 hover:bg-gray-800 hover:text-yellow-400'}`}
             >
              <Users className="w-5 h-5 mr-3" />
              Khách hàng
            </button>
             <button 
                onClick={() => {
                  setActiveTab('timekeeping');
                  setSelectedEmployee(null); // Reset detail view when switching tab
                }}
                className={`flex items-center w-full px-4 py-3 rounded-lg font-medium transition-colors ${activeTab === 'timekeeping' ? 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30' : 'text-gray-300 hover:bg-gray-800 hover:text-yellow-400'}`}
             >
              <Clock className="w-5 h-5 mr-3" />
              Chấm công
            </button>
             <button 
                onClick={() => setActiveTab('revenue-expense')}
                className={`flex items-center w-full px-4 py-3 rounded-lg font-medium transition-colors ${activeTab === 'revenue-expense' ? 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30' : 'text-gray-300 hover:bg-gray-800 hover:text-yellow-400'}`}
             >
              <TableIcon className="w-5 h-5 mr-3" />
              Thu chi
            </button>
             <div className="my-4 border-b border-yellow-600/20"></div>
             <button className="flex items-center w-full px-4 py-3 text-blue-200 hover:bg-blue-800/50 hover:text-yellow-300 rounded-lg font-medium transition-colors">
              <Settings className="w-5 h-5 mr-3" />
              Cấu hình API
            </button>
          </nav>
        </div>

        <div className="p-4 border-t border-yellow-400/20 mt-auto">
          <div className="glass p-4 rounded-xl border border-yellow-400/20 mb-3 glow-yellow-hover">
             <p className="text-xs font-bold text-yellow-300/90 uppercase mb-2 tracking-wider">Kết nối hiện tại</p>
             <div className="flex items-center gap-2 mb-2">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-yellow-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-yellow-400"></span>
                </span>
                <span className="text-xs text-blue-200 font-semibold truncate" title={APP_ID}>ID: {APP_ID.substring(0, 8)}...</span>
             </div>
             <p className="text-xs text-blue-300/60 truncate font-mono" title={API_KEY}>Key: ••••••••••</p>
          </div>
          <button className="group flex items-center w-full px-4 py-2.5 text-blue-200/80 hover:text-yellow-300 hover:bg-gradient-to-r hover:from-red-500/20 hover:to-red-600/10 transition-all duration-300 text-sm font-semibold rounded-xl border border-transparent hover:border-red-400/30">
            <LogOut className="w-4 h-4 mr-2 group-hover:rotate-12 transition-transform" />
            <span>Đăng xuất</span>
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 lg:ml-64 p-4 lg:p-8">
        {/* Header (Mobile + Desktop) */}
        <header className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">
              {activeTab === 'sales' && 'Bán hàng'}
              {activeTab === 'customers' && 'Danh sách KH'}
              {activeTab === 'timekeeping' && 'Chấm công'}
              {activeTab === 'revenue-expense' && 'Thu chi'}
            </h1>
            <p className="text-blue-200 text-sm mt-1">
              Dữ liệu từ bảng: <span className="font-mono text-xs bg-blue-800/50 text-yellow-300 px-2 py-1 rounded-lg border border-yellow-400/40 backdrop-blur-sm">{getCurrentTableName()}</span>
            </p>
          </div>
          
          <div className="flex items-center gap-4">
             <button className="relative p-2 text-blue-200 hover:bg-blue-800/50 hover:text-yellow-300 rounded-full transition-all">
               <Bell className="w-5 h-5" />
               <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-yellow-400 rounded-full border-2 border-blue-900 animate-pulse"></span>
             </button>
             <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-yellow-400 to-yellow-500 flex items-center justify-center text-blue-950 text-xs font-bold ring-2 ring-yellow-400/50 shadow-lg">
               AD
             </div>
          </div>
        </header>

        {/* Error Alert */}
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-6 flex items-center">
             <span className="font-bold mr-2">Lỗi:</span> {error}
          </div>
        )}

        {/* Tab Navigation (Mobile Only - Simplified) */}
        <div className="lg:hidden mb-6 border-b border-yellow-400/30 flex overflow-x-auto bg-blue-900/50 backdrop-blur-sm">
           <button 
              onClick={() => setActiveTab('sales')}
              className={`px-4 py-3 text-sm font-medium whitespace-nowrap border-b-2 ${activeTab === 'sales' ? 'border-yellow-400 text-yellow-300' : 'border-transparent text-blue-200'}`}
           >
             Bán hàng
           </button>
           <button 
              onClick={() => setActiveTab('customers')}
              className={`px-4 py-3 text-sm font-medium whitespace-nowrap border-b-2 ${activeTab === 'customers' ? 'border-yellow-500 text-yellow-500' : 'border-transparent text-gray-500'}`}
           >
             Khách hàng
           </button>
           <button 
              onClick={() => {
                setActiveTab('timekeeping');
                setSelectedEmployee(null);
              }}
              className={`px-4 py-3 text-sm font-medium whitespace-nowrap border-b-2 ${activeTab === 'timekeeping' ? 'border-yellow-500 text-yellow-500' : 'border-transparent text-gray-500'}`}
           >
             Chấm công
           </button>
           <button 
              onClick={() => setActiveTab('revenue-expense')}
              className={`px-4 py-3 text-sm font-medium whitespace-nowrap border-b-2 ${activeTab === 'revenue-expense' ? 'border-yellow-500 text-yellow-500' : 'border-transparent text-gray-500'}`}
           >
             Thu chi
           </button>
        </div>

        {/* Content Area */}
        {activeTab === 'sales' && (
          <>
            {/* Stats are now based on filtered data */}
            <Stats stats={stats} />

            {/* Global Date Filter for Sales Tab */}
            <div className="glass p-5 rounded-2xl shadow-2xl border border-yellow-400/30 mb-6 flex flex-col sm:flex-row items-center justify-between gap-4 glow-yellow-hover animate-fade-in">
               <div className="flex items-center gap-3 text-yellow-300 font-bold">
                  <div className="p-2 bg-yellow-400/20 rounded-lg border border-yellow-400/30">
                    <Filter className="w-5 h-5 text-yellow-400" />
                  </div>
                  <span className="text-base">Bộ lọc thời gian</span>
               </div>
               
               <div className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto">
                  <div className="flex items-center gap-2 w-full sm:w-auto">
                    <span className="text-sm text-blue-100 whitespace-nowrap">Từ:</span>
                    <div className="relative w-full sm:w-auto">
                       <input 
                         type="date" 
                         className="pl-10 pr-4 py-2.5 bg-slate-800/70 border border-yellow-400/40 text-blue-100 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-yellow-400 w-full sm:w-auto backdrop-blur-sm shadow-lg hover:border-yellow-400/60 transition-all"
                         value={startDate}
                         onChange={(e) => setStartDate(e.target.value)}
                       />
                       <Calendar className="w-4 h-4 text-yellow-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
                    </div>
                  </div>
                  <div className="flex items-center gap-2 w-full sm:w-auto">
                    <span className="text-sm text-blue-100 whitespace-nowrap">Đến:</span>
                    <div className="relative w-full sm:w-auto">
                       <input 
                         type="date" 
                         className="pl-10 pr-4 py-2.5 bg-slate-800/70 border border-yellow-400/40 text-blue-100 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-yellow-400 w-full sm:w-auto backdrop-blur-sm shadow-lg hover:border-yellow-400/60 transition-all"
                         value={endDate}
                         onChange={(e) => setEndDate(e.target.value)}
                       />
                       <Calendar className="w-4 h-4 text-yellow-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
                    </div>
                  </div>
                  
                  {(startDate || endDate) && (
                    <button 
                       onClick={clearSalesDateFilter}
                       className="p-2 text-yellow-300 hover:bg-yellow-400/20 rounded-lg transition-colors border border-yellow-400/30"
                       title="Xóa bộ lọc ngày"
                    >
                       <X className="w-5 h-5" />
                    </button>
                  )}
               </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
               <div className="lg:col-span-3">
                 {/* Chart now receives filtered data */}
                 <SalesChart data={filteredSalesData} mapping={mapping} />
               </div>
            </div>

            {/* Table now receives filtered data, removed internal date filter logic */}
            <SalesTable 
              data={filteredSalesData} 
              isLoading={isLoading} 
              hiddenColumns={salesHiddenColumns}
            />
          </>
        )}

        {activeTab === 'customers' && (
          <>
             {/* Bộ đếm */}
             <div className="mb-6 grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                   <div>
                      <p className="text-blue-200 text-sm font-medium">Tổng số khách hàng</p>
                      <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">{filteredCustomerData.length}</h3>
                      {(startDateCustomer || endDateCustomer || selectedCustomerType) && (
                        <p className="text-xs text-yellow-300/70 mt-1">Đã lọc</p>
                      )}
                   </div>
                   <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                      <Users className="w-6 h-6 text-yellow-300" />
                   </div>
                </div>
             </div>

             {/* Bộ lọc */}
             <div className="bg-gradient-to-r from-blue-800/60 to-teal-800/60 p-4 rounded-xl shadow-xl border border-yellow-400/40 mb-6 flex flex-col sm:flex-row items-center justify-between gap-4 backdrop-blur-sm">
               <div className="flex items-center gap-2 text-yellow-300 font-semibold">
                 <Filter className="w-5 h-5 text-yellow-400" />
                 <span>Bộ lọc</span>
               </div>
               
               <div className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto">
                 {/* Date Filter */}
                 <div className="flex items-center gap-2 w-full sm:w-auto">
                   <span className="text-sm text-blue-100 whitespace-nowrap">Từ ngày:</span>
                   <div className="relative w-full sm:w-auto">
                     <input 
                       type="date" 
                       className="pl-8 pr-3 py-2 bg-blue-900/70 border border-yellow-400/40 text-blue-100 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-yellow-400 w-full sm:w-auto backdrop-blur-sm"
                       value={startDateCustomer}
                       onChange={(e) => setStartDateCustomer(e.target.value)}
                     />
                     <Calendar className="w-4 h-4 text-yellow-400/80 absolute left-2.5 top-1/2 -translate-y-1/2" />
                   </div>
                 </div>
                 <div className="flex items-center gap-2 w-full sm:w-auto">
                   <span className="text-sm text-blue-100 whitespace-nowrap">Đến ngày:</span>
                   <div className="relative w-full sm:w-auto">
                     <input 
                       type="date" 
                       className="pl-8 pr-3 py-2 bg-blue-900/70 border border-yellow-400/40 text-blue-100 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-yellow-400 w-full sm:w-auto backdrop-blur-sm"
                       value={endDateCustomer}
                       onChange={(e) => setEndDateCustomer(e.target.value)}
                     />
                     <Calendar className="w-4 h-4 text-yellow-400/80 absolute left-2.5 top-1/2 -translate-y-1/2" />
                   </div>
                 </div>
                 
                 {/* Customer Type Filter */}
                 <div className="flex items-center gap-2 w-full sm:w-auto">
                   <span className="text-sm text-blue-100 whitespace-nowrap">Loại KH:</span>
                   <select
                     value={selectedCustomerType}
                     onChange={(e) => setSelectedCustomerType(e.target.value)}
                     className="bg-blue-900/70 text-blue-100 font-medium focus:outline-none focus:ring-2 focus:ring-yellow-400 border border-yellow-400/40 rounded px-3 py-2 min-w-[150px] w-full sm:w-auto backdrop-blur-sm"
                   >
                     <option value="">Tất cả loại</option>
                     {customerTypeList.map((type) => (
                       <option key={type} value={type}>
                         {type}
                       </option>
                     ))}
                   </select>
                 </div>
                 
                 {/* Clear Filters Button */}
                 {(startDateCustomer || endDateCustomer || selectedCustomerType) && (
                   <button 
                     onClick={() => {
                       setStartDateCustomer('');
                       setEndDateCustomer('');
                       setSelectedCustomerType('');
                     }}
                     className="p-2 text-yellow-300 hover:bg-yellow-400/20 border border-yellow-400/30 rounded-lg transition-colors"
                     title="Xóa tất cả bộ lọc"
                   >
                     <X className="w-5 h-5" />
                   </button>
                 )}
               </div>
             </div>

             <SalesTable 
                data={filteredCustomerData} 
                isLoading={isLoading} 
                hiddenColumns={customerHiddenColumns}
                filterColumns={['Địa chỉ lưu trú hiện tại', 'Loại KH']}
             />
          </>
        )}

        {activeTab === 'timekeeping' && (
          <>
             {/* Master View: Summary List */}
             {!selectedEmployee ? (
               <>
                {/* Header & Filter */}
                <div className="flex flex-col gap-4 mb-6">
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 flex-1">
                      <div className="flex items-center gap-2 bg-gradient-to-r from-blue-800/60 to-teal-800/60 px-4 py-2 rounded-lg border border-yellow-400/40 shadow-lg backdrop-blur-sm">
                        <Filter className="w-4 h-4 text-yellow-400" />
                        <span className="text-sm text-yellow-300 font-medium whitespace-nowrap">Lọc Tháng:</span>
                        <input 
                            type="month" 
                            value={selectedMonth}
                            onChange={(e) => setSelectedMonth(e.target.value)}
                            className="bg-blue-900/70 border border-yellow-400/40 text-blue-100 rounded text-sm font-medium focus:outline-none focus:ring-2 focus:ring-yellow-400 w-full px-2 py-1 backdrop-blur-sm"
                        />
                      </div>
                      
                      <div className="flex items-center gap-2 bg-gradient-to-r from-blue-800/60 to-teal-800/60 px-4 py-2 rounded-lg border border-yellow-400/40 shadow-lg backdrop-blur-sm">
                        <Users className="w-4 h-4 text-yellow-400 flex-shrink-0" />
                        <span className="text-sm text-yellow-300 font-medium whitespace-nowrap flex-shrink-0">Lọc Nhân sự:</span>
                        <select
                            value={selectedEmployeeFilter}
                            onChange={(e) => setSelectedEmployeeFilter(e.target.value)}
                            className="bg-blue-900/70 text-blue-100 font-medium focus:outline-none focus:ring-2 focus:ring-yellow-400 border border-yellow-400/40 rounded px-3 py-1.5 min-w-[180px] flex-1 backdrop-blur-sm"
                            disabled={employeeListForFilter.length === 0}
                        >
                          <option value="">Tất cả nhân sự ({employeeListForFilter.length})</option>
                          {employeeListForFilter.length > 0 ? (
                            employeeListForFilter.map((empName) => (
                              <option key={empName} value={empName}>
                                {empName}
                              </option>
                            ))
                          ) : (
                            <option value="" disabled>
                              {timekeepingMapping.employeeField 
                                ? 'Chưa có dữ liệu trong tháng này' 
                                : 'Đang tải dữ liệu...'}
                            </option>
                          )}
                        </select>
                        {selectedEmployeeFilter && (
                          <button
                            onClick={() => setSelectedEmployeeFilter('')}
                            className="ml-2 p-1.5 text-red-500 hover:bg-red-50 rounded transition-colors flex-shrink-0"
                            title="Xóa bộ lọc nhân sự"
                          >
                            <X className="w-4 h-4" />
                          </button>
                        )}
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-2">
                       <button 
                          onClick={handleExportSummary}
                          className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-yellow-400 to-yellow-500 text-blue-950 rounded-lg text-sm font-medium hover:from-yellow-300 hover:to-yellow-400 transition-colors shadow-xl whitespace-nowrap font-bold"
                       >
                         <Download className="w-4 h-4" />
                         <span className="hidden sm:inline">Xuất Excel</span>
                       </button>
                    </div>
                  </div>
                </div>

                {/* Bộ đếm theo bộ lọc tháng + nhân sự */}
                <div className="mb-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                    <div>
                      <p className="text-blue-200 text-sm font-medium">Tổng số nhân sự</p>
                      <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">{totalEmployees}</h3>
                      <p className="text-xs text-yellow-300/70 mt-1">Tháng {selectedMonth}</p>
                    </div>
                    <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                      <Users className="w-6 h-6 text-yellow-300" />
                    </div>
                  </div>

                  <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                    <div>
                      <p className="text-blue-200 text-sm font-medium">Tổng số lần chấm</p>
                      <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">{grandTotalDays}</h3>
                      <p className="text-xs text-yellow-300/70 mt-1">Từ dữ liệu chi tiết</p>
                    </div>
                    <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                      <Clock className="w-6 h-6 text-yellow-300" />
                    </div>
                  </div>

                  <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                    <div>
                      <p className="text-blue-200 text-sm font-medium">Tổng giờ làm việc</p>
                      <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">{grandTotalHours.toFixed(1)}</h3>
                      <p className="text-xs text-yellow-300/70 mt-1">Giờ</p>
                    </div>
                    <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                      <Clock className="w-6 h-6 text-yellow-300" />
                    </div>
                  </div>

                  <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                    <div>
                      <p className="text-blue-200 text-sm font-medium">TB giờ/nhân sự</p>
                      <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">
                        {totalEmployees > 0 
                          ? (grandTotalHours / totalEmployees).toFixed(1) 
                          : '0.0'}
                      </h3>
                      <p className="text-xs text-yellow-300/70 mt-1">Giờ/người</p>
                    </div>
                    <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                      <Clock className="w-6 h-6 text-yellow-300" />
                    </div>
                  </div>
                </div>

                {/* Raw Data Table (Filtered) */}
                <div className="mt-8">
                  <h3 className="text-md font-semibold text-yellow-300 mb-4 px-1">
                    Dữ liệu thô (Toàn bộ)
                    {selectedEmployeeFilter && (
                      <span className="ml-2 text-sm text-yellow-400 font-normal">
                        - Đã lọc: {selectedEmployeeFilter}
                      </span>
                    )}
                  </h3>
                  <SalesTable 
                     data={filteredTimekeepingDataByEmployee} 
                     isLoading={isLoading}
                     hiddenColumns={['id', '_RowNumber', 'Checkout', 'Ảnh', 'vị trí', 'Vị trí']} 
                  />
                </div>
               </>
             ) : (
               /* Detail View: Employee Specific */
               <>
                 <button 
                   onClick={() => setSelectedEmployee(null)}
                   className="group flex items-center gap-2 text-blue-200/80 hover:text-yellow-300 mb-6 transition-all duration-300 font-semibold"
                 >
                   <ChevronLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
                   <span>Quay lại danh sách</span>
                 </button>

                 <div className="glass rounded-2xl shadow-2xl border border-yellow-400/30 overflow-hidden animate-fade-in">
                   {/* Header Detail */}
                   <div className="p-7 border-b border-yellow-400/20 bg-gradient-to-r from-slate-800/60 to-blue-800/60 flex items-center gap-5 backdrop-blur-sm">
                     <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-yellow-400/30 to-yellow-500/20 border border-yellow-400/40 flex items-center justify-center text-2xl font-black text-yellow-300 shadow-lg">
                       {selectedEmployee.charAt(0).toUpperCase()}
                     </div>
                     <div className="flex-1">
                       <h2 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent mb-1">{selectedEmployee}</h2>
                       <p className="text-blue-200/70 text-sm font-medium">Chi tiết chấm công tháng {selectedMonth}</p>
                     </div>
                     <div className="ml-auto flex gap-6 text-sm">
                       <div className="text-right">
                         <p className="text-blue-200/60 text-xs uppercase font-bold tracking-wider mb-1">Tổng lượt chấm</p>
                         <p className="font-extrabold text-2xl text-yellow-300">
                           {(() => {
                             const details = employeeDetailsMap[selectedEmployee];
                             if (!details || details.length === 0) return 0;
                             return details.reduce((acc: number, cur: any) => {
                               const count = cur.checkCount || 0;
                               return acc + count;
                             }, 0);
                           })()}
                         </p>
                       </div>
                       <div className="text-right">
                         <p className="text-blue-200/60 text-xs uppercase font-bold tracking-wider mb-1">Tổng giờ</p>
                         <p className="font-extrabold text-2xl bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">
                           {(() => {
                             const details = employeeDetailsMap[selectedEmployee];
                             if (!details || details.length === 0) return '0.0';
                             const total = details.reduce((acc: number, cur: any) => acc + (cur.hours || 0), 0);
                             return total.toFixed(1);
                           })()}
                         </p>
                       </div>
                     </div>
                   </div>

                   {/* Daily Breakdown Table */}
                   <div className="overflow-x-auto custom-scrollbar">
                     <table className="w-full text-left border-collapse">
                       <thead>
                         <tr className="bg-gradient-to-r from-slate-800/80 to-blue-800/60 text-yellow-300 text-xs uppercase font-bold tracking-wider border-b border-yellow-400/30 backdrop-blur-sm">
                           <th className="px-6 py-4 w-1/4">Ngày</th>
                           <th className="px-6 py-4 text-center">Giờ vào</th>
                           <th className="px-6 py-4 text-center">Giờ ra</th>
                           <th className="px-6 py-4 text-center">Số lần chấm</th>
                           <th className="px-6 py-4 text-right">Tổng giờ</th>
                         </tr>
                       </thead>
                       <tbody className="divide-y divide-yellow-400/5 text-sm">
                         {employeeDetailsMap[selectedEmployee] && employeeDetailsMap[selectedEmployee].length > 0 ? (
                           employeeDetailsMap[selectedEmployee].map((day: any, idx: number) => (
                             <tr key={idx} className="group hover:bg-gradient-to-r hover:from-blue-800/30 hover:to-slate-800/30 transition-all duration-200 border-b border-yellow-400/5">
                               <td className="px-6 py-4 font-semibold text-blue-100 group-hover:text-yellow-200 transition-colors">
                                 {(() => {
                                   const date = parseDate(day.date);
                                   return date ? date.toLocaleDateString('vi-VN', { weekday: 'short', day: '2-digit', month: '2-digit', year: 'numeric' }) : day.date;
                                 })()}
                               </td>
                               <td className="px-6 py-4 text-center text-blue-200/80 font-mono bg-slate-800/30 group-hover:bg-yellow-400/10 transition-colors">
                                 {day.checkIn ? day.checkIn.toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) : '--:--'}
                               </td>
                               <td className="px-6 py-4 text-center text-blue-200/80 font-mono bg-slate-800/30 group-hover:bg-yellow-400/10 transition-colors">
                                 {day.checkOut ? day.checkOut.toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) : '--:--'}
                               </td>
                               <td className="px-6 py-4 text-center">
                                 <span className={`inline-flex items-center justify-center w-8 h-8 rounded-xl text-xs font-bold shadow-lg ${
                                   day.checkCount === 2 
                                     ? 'bg-gradient-to-br from-yellow-400/30 to-yellow-500/20 text-yellow-300 border border-yellow-400/40' 
                                     : 'bg-red-500/20 text-red-300 border border-red-400/30'
                                 }`}>
                                   {day.checkCount}
                                 </span>
                               </td>
                               <td className="px-6 py-4 text-right font-bold">
                                 {day.checkCount === 2 ? (
                                    <span className="text-yellow-300 text-base">{day.hours.toFixed(2)} giờ</span>
                                 ) : (
                                    <span className="text-red-400/70 text-xs italic">Không tính</span>
                                 )}
                               </td>
                             </tr>
                           ))
                         ) : (
                           <tr>
                             <td colSpan={5} className="px-6 py-16 text-center">
                               <div className="flex flex-col items-center gap-3">
                                 <div className="p-4 bg-yellow-400/10 rounded-full border border-yellow-400/20">
                                   <AlertCircle className="w-10 h-10 text-yellow-400/60" />
                                 </div>
                                 <p className="text-yellow-200/80 font-medium">Không có dữ liệu chi tiết.</p>
                               </div>
                             </td>
                           </tr>
                         )}
                       </tbody>
                     </table>
                   </div>
                   <div className="p-5 bg-gradient-to-r from-yellow-400/10 to-yellow-500/5 border-t border-yellow-400/30 text-yellow-200/90 text-xs flex items-center gap-3 backdrop-blur-sm">
                      <AlertCircle className="w-5 h-5 text-yellow-400 flex-shrink-0" />
                      <span className="font-semibold">Lưu ý:</span> Hệ thống chỉ tính tổng giờ khi phát hiện đúng 2 lần chấm công (Vào/Ra) trong ngày.
                   </div>
                 </div>
               </>
             )}
          </>
        )}

        {activeTab === 'revenue-expense' && (
          <>
            {/* Stats Cards */}
            <div className="mb-6 grid grid-cols-1 md:grid-cols-4 gap-6">
              <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                <div>
                  <p className="text-blue-200 text-sm font-medium">Tổng thu</p>
                  <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">
                    {CURRENCY_FORMAT.format(revenueStats.totalAmount)}
                  </h3>
                  {(startDateRevenueExpense || endDateRevenueExpense) && (
                    <p className="text-xs text-yellow-300/70 mt-1">Đã lọc</p>
                  )}
                </div>
                <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                  <ArrowRight className="w-6 h-6 text-yellow-300 rotate-[-45deg]" />
                </div>
              </div>

              <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                <div>
                  <p className="text-blue-200 text-sm font-medium">Tổng chi</p>
                  <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">
                    {CURRENCY_FORMAT.format(expenseStats.totalAmount)}
                  </h3>
                  {(startDateRevenueExpense || endDateRevenueExpense) && (
                    <p className="text-xs text-yellow-300/70 mt-1">Đã lọc</p>
                  )}
                </div>
                <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                  <ArrowRight className="w-6 h-6 text-yellow-300 rotate-[45deg]" />
                </div>
              </div>

              <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                <div>
                  <p className="text-blue-200 text-sm font-medium">Lợi nhuận</p>
                  <h3 className={`text-2xl font-bold ${netAmount >= 0 ? 'bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent' : 'text-red-400'}`}>
                    {CURRENCY_FORMAT.format(netAmount)}
                  </h3>
                  {(startDateRevenueExpense || endDateRevenueExpense) && (
                    <p className="text-xs text-yellow-300/70 mt-1">Đã lọc</p>
                  )}
                </div>
                <div className={`p-3 rounded-lg border ${netAmount >= 0 ? 'bg-yellow-400/20 border-yellow-400/30' : 'bg-red-500/20 border-red-500/30'} shadow-lg`}>
                  <TableIcon className={`w-6 h-6 ${netAmount >= 0 ? 'text-yellow-300' : 'text-red-400'}`} />
                </div>
              </div>

              <div className="bg-gradient-to-br from-blue-800/70 to-teal-800/70 p-6 rounded-xl shadow-xl border border-yellow-400/40 flex items-center justify-between backdrop-blur-sm">
                <div>
                  <p className="text-blue-200 text-sm font-medium">Tổng giao dịch</p>
                  <h3 className="text-2xl font-bold bg-gradient-to-r from-yellow-300 to-yellow-400 bg-clip-text text-transparent">{revenueStats.totalRecords + expenseStats.totalRecords}</h3>
                  {(startDateRevenueExpense || endDateRevenueExpense) && (
                    <p className="text-xs text-yellow-300/70 mt-1">Đã lọc</p>
                  )}
                </div>
                <div className="p-3 bg-yellow-400/20 border border-yellow-400/30 rounded-lg shadow-lg">
                  <List className="w-6 h-6 text-yellow-300" />
                </div>
              </div>
            </div>

            {/* Date Filter */}
            <div className="bg-gradient-to-r from-blue-800/60 to-teal-800/60 p-4 rounded-xl shadow-xl border border-yellow-400/40 mb-6 flex flex-col sm:flex-row items-center justify-between gap-4 backdrop-blur-sm">
              <div className="flex items-center gap-2 text-yellow-300 font-semibold">
                <Filter className="w-5 h-5 text-yellow-400" />
                <span>Bộ lọc thời gian</span>
              </div>
              
              <div className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto">
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <span className="text-sm text-blue-100 whitespace-nowrap">Từ:</span>
                  <div className="relative w-full sm:w-auto">
                    <input 
                      type="date" 
                      className="pl-8 pr-3 py-2 bg-blue-900/70 border border-yellow-400/40 text-blue-100 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-yellow-400 w-full sm:w-auto backdrop-blur-sm"
                      value={startDateRevenueExpense}
                      onChange={(e) => setStartDateRevenueExpense(e.target.value)}
                    />
                    <Calendar className="w-4 h-4 text-yellow-400/80 absolute left-2.5 top-1/2 -translate-y-1/2" />
                  </div>
                </div>
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <span className="text-sm text-blue-100 whitespace-nowrap">Đến:</span>
                  <div className="relative w-full sm:w-auto">
                    <input 
                      type="date" 
                      className="pl-8 pr-3 py-2 bg-blue-900/70 border border-yellow-400/40 text-blue-100 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-yellow-400 w-full sm:w-auto backdrop-blur-sm"
                      value={endDateRevenueExpense}
                      onChange={(e) => setEndDateRevenueExpense(e.target.value)}
                    />
                    <Calendar className="w-4 h-4 text-yellow-400/80 absolute left-2.5 top-1/2 -translate-y-1/2" />
                  </div>
                </div>
                
                {(startDateRevenueExpense || endDateRevenueExpense) && (
                  <button 
                    onClick={() => {
                      setStartDateRevenueExpense('');
                      setEndDateRevenueExpense('');
                    }}
                    className="p-2 text-yellow-300 hover:bg-yellow-400/20 border border-yellow-400/30 rounded-lg transition-colors"
                    title="Xóa bộ lọc ngày"
                  >
                    <X className="w-5 h-5" />
                  </button>
                )}
              </div>
            </div>

            {/* Two Tables Side by Side */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Revenue Table */}
              <div>
                <div className="bg-gradient-to-r from-yellow-400/30 to-yellow-500/30 border border-yellow-400/50 rounded-t-xl px-6 py-4 flex items-center justify-between backdrop-blur-sm">
                  <h2 className="text-lg font-semibold text-yellow-200 flex items-center gap-2">
                    <ArrowRight className="w-5 h-5 rotate-[-45deg]" />
                    Bảng Thu ({revenueStats.totalRecords} giao dịch)
                  </h2>
                  <span className="text-sm font-bold text-yellow-300">
                    {CURRENCY_FORMAT.format(revenueStats.totalAmount)}
                  </span>
                </div>
                <div className="border border-yellow-400/30 border-t-0 rounded-b-xl overflow-hidden">
                  <SalesTable 
                    data={filteredRevenueData} 
                    isLoading={isLoading} 
                    hiddenColumns={revenueExpenseHiddenColumns}
                  />
                </div>
              </div>

              {/* Expense Table */}
              <div>
                <div className="bg-gradient-to-r from-yellow-400/30 to-yellow-500/30 border border-yellow-400/50 rounded-t-xl px-6 py-4 flex items-center justify-between backdrop-blur-sm">
                  <h2 className="text-lg font-semibold text-yellow-200 flex items-center gap-2">
                    <ArrowRight className="w-5 h-5 rotate-[45deg]" />
                    Bảng Chi ({expenseStats.totalRecords} giao dịch)
                  </h2>
                  <span className="text-sm font-bold text-yellow-300">
                    {CURRENCY_FORMAT.format(expenseStats.totalAmount)}
                  </span>
                </div>
                <div className="border border-yellow-400/30 border-t-0 rounded-b-xl overflow-hidden">
                  <SalesTable 
                    data={filteredExpenseData} 
                    isLoading={isLoading} 
                    hiddenColumns={revenueExpenseHiddenColumns}
                  />
                </div>
              </div>
            </div>
          </>
        )}
        
        <footer className="mt-12 mb-4 text-center">
          <div className="inline-flex items-center gap-2 px-6 py-3 glass rounded-xl border border-yellow-400/20">
            <span className="text-xs text-blue-200/60 font-medium">
              © 2024 <span className="text-yellow-300 font-semibold">Anh Công nhân</span> System
            </span>
            <span className="w-1 h-1 rounded-full bg-yellow-400/40"></span>
            <span className="text-xs text-blue-200/60 font-mono">
              App ID: {APP_ID.substring(0, 8)}...
            </span>
          </div>
        </footer>
      </main>
    </div>
  );
};

export default App;
